# Sample Configuration for new TSDB

# The IP address or hostname the server should listen on (e.g. 127.0.0.1 or 0.0.0.0)
addr = "0.0.0.0"

# The port number on which the server should accept requests
#
# This is the public-facing port used by browsers or other apps to connect to your server.
# Make sure this port is not blocked by your system's firewall.
# Avoid using ports below 1024 unless your app runs as root (e.g. 80 or 443).
#
port = 3000

# Gossip port
gossip_port = 5000

# A unique name or ID that identifies this server node in a cluster
node_id = "node-a"

# The HTTP URL that this node advertises to peers (e.g. http://localhost:3000)
self_url = "http://localhost:3000"

# URLs of other nodes in the network that this node can communicate with
bootstrap_peers = ["http://localhost:3001", "http://localhost:3002"]

# Path to the folder where the app will store data files. Default is "./tddb"
data_dir = "./tsdb"
